[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[dependencies]

# 声明多个二进制目标
[[bin]]
name = "main3"
path = "src/demo/main3.rs"

[[bin]]
name = "main4"
path = "src/demo/main4.rs"

[[bin]]
name = "main1"
path = "src/main1.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"
