[workspace]

members = ["rust-demo", "rust-async", "rust-lib", "rust-thread"]

resolver = "2"

[workspace.dependencies]
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
